### ISSUE TITLE
Bevy features instead of individual crates

### ISSUE THREAD

**Issue by bakcxoj** [BrandonDyer64/bevy_wasm#5]
Right now, all of the necessary bevy crates are imported individually.

```toml
bevy_app = "0.9"
bevy_ecs = "0.9"
bevy_log = "0.9"
```

Instead, this should be done through Bevy's features.

```toml
features = ["app", "ecs", "log"]
```
